docs: refactor several areas of documentation
authelia/authelia pull request #1726
Opened 2021-02-15 06:10 UTC by james-d-elliott

Updated all links to use https://www.authelia.com/docs/.
Removed all comment sections from documented configuration on the documentation site and replaced them with their own sections.
Made all documentation inside config.template.yml double hashes, and made all commented configuration sections single quoted.
Added .yamllint.yaml to express our desired YAML styles.
Added a style guide.
Refactored many documentation areas to be 120 char widths where possible. It's by no means exhaustive but is a large start.
Added a statelessness guide for the pending Kubernetes chart introduction.

2021-03-16 20:43 UTC, clems4ever approved these changes
Only tiny things that can be handled in another review if needed.

2021-03-16 20:43 UTC, clems4ever commented on README.md
> +Authelia exists thanks to all the people who contribute so don't be shy, come chat with us on [Matrix](#matrix) and
Add Discord here

2021-03-16 20:43 UTC, clems4ever commented on README.md
> +for providing us with free licenses to their great tools
```suggestion
for providing us with free licenses to their great tools.
```

2021-04-07 07:31 UTC, nightah requested changes
Gone through a pass and suggested a handful of changes.

Other things which we've discussed but to be addressed:
* Ensure that `configuration.yml` `users_database.yml` and `certificate.yml` for the local and lite bundles are reinstated
* Update `examples/compose/local/setup.sh` to include the executable bit: `git update-index --chmod=755 examples/compose/local/setup.sh`

2021-04-07 07:31 UTC, nightah commented on config.template.yml
> +## This mechanism prevents attackers from brute forcing the first factor. It bans the user if too many attempts are done
```suggestion
## This mechanism prevents attackers from brute forcing the first factor. It bans the user if too many attempts are made
```

2021-04-07 07:31 UTC, nightah commented on config.template.yml
> +## Notifications are sent to users when they require a password reset, a u2f registration or a TOTP registration.
```suggestion
## Notifications are sent to users when they require a password reset, a U2F registration or a TOTP registration.
```

2021-04-07 07:31 UTC, nightah commented on config.template.yml
> +## The available providers are: filesystem, smtp. You must use one and only one of these providers.
```suggestion
## The available providers are: filesystem, smtp. You must use only one of these providers.
```

2021-04-07 07:31 UTC, nightah commented on docs/_config.yml
> +footer_content: "Copyright &copy; 2021 Authelia. Distributed by an <a href=\"https://github.com/authelia/authelia/blob/master/LICENSE\">Apache 2.0 license.</a>"
Probably worth also updating the email here to `team@authelia.com`.

2021-04-07 07:31 UTC, nightah commented on docs/community/using-remote-user-header-for-sso-with-jira.md
>  First of all, users should exist on both authelia and Jira AND have the same
```suggestion
First of all, users should exist on both Authelia and Jira, and have the same
```

2021-04-07 07:31 UTC, nightah commented on docs/community/using-remote-user-header-for-sso-with-jira.md
> +  - Add `traefik.http.routers.jira.middlewares=authelia@docker` in the labels of Jira (to actually enable authelia for
```suggestion
  - Add `traefik.http.routers.jira.middlewares=authelia@docker` in the labels of Jira (to actually enable Authelia for 
```

2021-04-07 07:31 UTC, nightah commented on docs/community/using-remote-user-header-for-sso-with-jira.md
> +    the jira instance)
```suggestion
    the Jira instance)
```

2021-04-07 07:31 UTC, nightah commented on docs/configuration/miscellaneous.md
> +security on lower areas of the OSI model. However it required, if you specify both of the tls options the port will
```suggestion
security on lower areas of the OSI model. However if required, when you specify both of the tls options the port will 
```

2021-04-07 07:31 UTC, nightah commented on docs/configuration/session/redis.md
> +we highly recommend it in production environments. It requires you setup [redis] as well.
```suggestion
we highly recommend it in production environments. It requires you to setup [redis] as well.
```

2021-04-07 07:31 UTC, nightah commented on docs/configuration/storage/sqlite.md
> +requires you setup an external database.
```suggestion
requires you to setup an external database.
```

2021-04-07 07:31 UTC, nightah commented on docs/contributing/authelia-scripts.md
> +Authelia comes with a set of dedicated scripts doing a broad range of operations such as building the distributed
```suggestion
Authelia comes with a set of dedicated scripts to perform a broad range of operations such as building the distributed 
```

2021-04-07 07:31 UTC, nightah commented on docs/contributing/authelia-scripts.md
>  Those scripts becomes available after sourcing the bootstrap.sh script with
```suggestion
Those scripts become available after sourcing the bootstrap.sh script with
```

2021-04-07 07:31 UTC, nightah commented on docs/contributing/build-and-dev.md
> +In order to build and contribute to **Authelia**, you need to make sure Go >= v1.13, Docker, docker-compose and
```suggestion
In order to build and contribute to **Authelia**, you need to make sure Go >= v1.16, Docker, docker-compose and 
```

2021-04-07 07:31 UTC, nightah commented on docs/contributing/style-guide.md
> +- [golangci-lint](https://github.com/golangci/golangci-lint)
We should also add eslint in here as that enforces style for all `js` `ts` and `tsx` files along with prettier.

2021-04-07 07:31 UTC, nightah commented on internal/configuration/config.template.yml
> +---
I'm not going to recomment all the suggestions from the root `config.template.yml` but just a note to ensure you copy the changes over when/if accepted.

2021-04-11 09:55 UTC, nightah approved these changes
LGTM!

2021-04-11 11:25 UTC, merged