docs: refactor access control configuration sections
authelia/authelia pull request #1945
Opened 2021-04-24 07:25 UTC by james-d-elliott

Refactors the access-control configuration documentation to be up-to-date and conform to our style guidelines. Additionally went over each part and reworded things that needed it.

2021-06-19 09:17 UTC, clems4ever submitted a review, later dismissed
Tiny remarks otherwise LGTM.

2021-06-19 11:19 UTC, james-d-elliott commented on docs/configuration/access-control.md
> +policy output given input of a users request and a rule list in the future.*
Yeah that's a good idea.

2021-06-22 05:17 UTC, james-d-elliott commented on docs/configuration/access-control.md
> +It's important to note that Authelia cannot preserve request data when redirecting the user. For example if the user had
Thanks, felt like it was essential we communicate this clearly.

2021-06-22 05:52 UTC, nightah requested changes
Two tiny nits, otherwise LGTM.

2021-06-22 05:52 UTC, nightah commented on docs/configuration/access-control.md
> +This configuration option *does nothing* by itself, it's only useful if you use theese aliases in the [rules](#networks)
```suggestion
This configuration option *does nothing* by itself, it's only useful if you use these aliases in the [rules](#networks)
```

2021-06-22 05:52 UTC, nightah commented on docs/configuration/access-control.md
> +This criteria is a list of network address ranges in CIDR notation or an alias from the [global](#networks-global)
The network addresses do not need to be in CIDR notation, they can be singlular IP addresses or CIDR notation.

2021-06-22 05:59 UTC, nightah approved these changes

2021-06-22 06:00 UTC, merged