fix(storage): use lower case in error messages
authelia/authelia pull request #2145
Opened 2021-07-03 15:25 UTC by clems4ever

2021-07-03 21:45 UTC, james-d-elliott approved these changes
LGTM

2021-07-03 22:09 UTC, james-d-elliott requested changes
More of a question actually instead of a request for changes, but wanted to make sure it's seen. I think there is a difference in returned errors and logged messages, do we want to affect both?

2021-07-04 18:53 UTC, clems4ever commented
> More of a question actually instead of a request for changes, but wanted to make sure it's seen. I think there is a difference in returned errors and logged messages, do we want to affect both?

I was mainly fixing the warnings in the IDE due to upper case in error messages but yes, why not also do the logs. I'll update the PR.

2021-07-04 20:38 UTC, james-d-elliott commented
> 
> 
> > More of a question actually instead of a request for changes, but wanted to make sure it's seen. I think there is a difference in returned errors and logged messages, do we want to affect both?
> 
> I was mainly fixing the warnings in the IDE due to upper case in error messages but yes, why not also do the logs. I'll update the PR.

Ah makes sense.

2021-07-04 20:38 UTC, james-d-elliott approved these changes

2021-08-03 22:10 UTC, nightah requested changes
For consistency let's not lower case our log messages.

2021-08-03 22:10 UTC, nightah commented on internal/storage/mysql_provider.go
> +		provider.log.Fatalf("unable to connect to SQL database: %v", err)
```suggestion
		provider.log.Fatalf("Unable to connect to SQL database: %v", err)
```

2021-08-03 22:10 UTC, nightah commented on internal/storage/mysql_provider.go
> +		provider.log.Fatalf("unable to initialize SQL database: %v", err)
```suggestion
		provider.log.Fatalf("Unable to initialize SQL database: %v", err)
```

2021-08-03 22:10 UTC, nightah commented on internal/storage/postgres_provider.go
> +		provider.log.Fatalf("unable to connect to SQL database: %v", err)
```suggestion
		provider.log.Fatalf("Unable to connect to SQL database: %v", err)
```

2021-08-03 22:10 UTC, nightah commented on internal/storage/postgres_provider.go
> +		provider.log.Fatalf("unable to initialize SQL database: %v", err)
```suggestion
		provider.log.Fatalf("Unable to initialize SQL database: %v", err)
```

2021-08-03 22:10 UTC, nightah commented on internal/storage/sqlite_provider.go
> +		provider.log.Fatalf("unable to create SQL database %s: %s", path, err)
```suggestion
		provider.log.Fatalf("Unable to create SQL database %s: %s", path, err)
```

2021-08-03 22:10 UTC, nightah commented on internal/storage/sqlite_provider.go
> +		provider.log.Fatalf("unable to initialize SQL database %s: %s", path, err)
```suggestion
		provider.log.Fatalf("Unable to initialize SQL database %s: %s", path, err)
```

2021-08-03 22:10 UTC, nightah commented on internal/storage/sqlmock_provider.go
> +		provider.log.Fatalf("unable to create SQL database: %s", err)
```suggestion
		provider.log.Fatalf("Unable to create SQL database: %s", err)
```

2021-08-03 22:52 UTC, james-d-elliott approved these changes
LGTM

2021-08-03 23:36 UTC, merged