Case server
authelia/authelia pull request #2151
Opened 2021-07-05 20:56 UTC by clems4ever

2021-07-08 01:44 UTC, nightah requested changes
Capitalizing just this element looks a bit odd.
WDYT?

2021-07-08 01:44 UTC, nightah commented on internal/server/error_handler.go
> +		logger.Tracef("request was too large to handle from client %s. Response Code %d.", ctx.RemoteIP().String(), fasthttp.StatusRequestHeaderFieldsTooLarge)
```suggestion
		logger.Tracef("request was too large to handle from client %s. response dode %d.", ctx.RemoteIP().String(), fasthttp.StatusRequestHeaderFieldsTooLarge)
```

2021-07-08 01:44 UTC, nightah commented on internal/server/error_handler.go
> +		logger.Tracef("request timeout occurred while handling from client %s: %s. Response Code %d.", ctx.RemoteIP().String(), ctx.RequestURI(), fasthttp.StatusRequestTimeout)
```suggestion
		logger.Tracef("request timeout occurred while handling from client %s: %s. response code %d.", ctx.RemoteIP().String(), ctx.RequestURI(), fasthttp.StatusRequestTimeout)
```

2021-07-08 01:44 UTC, nightah commented on internal/server/error_handler.go
> +		logger.Tracef("an unknown error occurred while handling a request from client %s: %s. Response Code %d.", ctx.RemoteIP().String(), ctx.RequestURI(), fasthttp.StatusBadRequest)
```suggestion
		logger.Tracef("an unknown error occurred while handling a request from client %s: %s. response code %d.", ctx.RemoteIP().String(), ctx.RequestURI(), fasthttp.StatusBadRequest)
```

2021-07-08 01:47 UTC, james-d-elliott commented
> 
> 
> Capitalizing just this element looks a bit odd.
> WDYT?

Probably a good idea if we make everything lowercase except maybe acronyms or other reasonable exceptions?

2021-07-12 16:42 UTC, clems4ever commented
I'm fine with both propositions. I've committed the suggestions.

2021-08-03 22:11 UTC, nightah requested changes
For consistency lets not lower case log messages.

2021-08-03 22:50 UTC, james-d-elliott approved these changes
LGTM

2021-08-03 23:18 UTC, merged