feat(storage): encrypted secret values
authelia/authelia pull request #2588
Opened 2021-11-10 10:27 UTC by james-d-elliott

This adds an AES-GCM 256bit encryption layer for storage for sensitive items. This is only TOTP secrets for the time being but this may be expanded later.

Closes #682

2021-11-23 10:26 UTC, Ornias1993 commented
Assume this is going to be next sem-ver major?

2021-11-23 10:43 UTC, james-d-elliott commented on docs/configuration/storage/sqlite.md
>  ```
Needs link to the encryption key docs.

2021-11-23 10:43 UTC, james-d-elliott commented on internal/commands/root.go
>  	switch {
```suggestion
	storageProvider = getStorageProvider()
```

2021-11-23 10:43 UTC, james-d-elliott commented on internal/commands/helpers.go
>  		return nil, errors.New("no storage provider configured")
```suggestion
		return nil
```

This makes the func more universally useful.

2021-11-23 10:43 UTC, james-d-elliott commented on internal/commands/helpers.go
>  func getStorageProvider() (provider storage.Provider, err error) {
```suggestion
func getStorageProvider() (provider storage.Provider) {
```

This makes the func more universally useful.

2021-11-23 10:47 UTC, nightah requested changes
Only found one small issue with what's there. Other than that I suspect we need to update all suite configurations to include an encryption key too?

2021-11-23 10:47 UTC, nightah commented on docs/configuration/storage/sqlite.md
> +  encryption_key: a_very_important_secret
There's no reference to the encryption key option linking back to the other doc for this this storage type.

2021-11-23 10:48 UTC, james-d-elliott commented
> 

This will be a minor. Additionally:

1. It will be automatically applied as a migration to the database and will require the encryption key is specified.
2. There will be a migration down option via the CLI.
3. There will be an export option to both csv and OTP URI's that can be used to generate a QR code.
4. There will be a CLI option to allow users to change the encryption key on all encrypted fields.
5. The encryption algorithm is an open standard.

2021-11-23 11:22 UTC, Ornias1993 commented
> > Assume this is going to be next sem-ver major? Or is the enc optional?
> 
> @Ornias1993
> 
> This will be a minor. Additionally:
> 
> 1. It will be automatically applied as a migration to the database and will require the encryption key is specified either in configuration or as an ENV var secret `AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE`.
> 2. There will be a down migration option via the CLI.
> 3. There will be an export option to both CSV and OTP URI's that can be used to generate a QR code (if you'd like to see some mock output, let me know).
> 4. There will be a CLI option to allow users to change the encryption key on all encrypted fields.
> 5. The encryption algorithm is an open standard.

Sorry, but for everyone deploying this in any sort of significant environment this is going to be a major.
As things like HelmCharts and configs needs to be rewrithen to use an actually decent encryption key.

2021-11-23 23:48 UTC, james-d-elliott commented
Could you potentially elaborate on what elements of the change constitute the breaking change? Is it the config option, or that the config option is required? Or is it the database schema changing? I will discuss this with the team again either way.

> we would then need to write all sorts of migration tools to move to actually use a good (or user provided) encryption key.

I mean the pattern to achieve this already exists and all of the tooling is available in Helm. Changing the version will not in any way affect this.

2021-11-25 01:29 UTC, nightah approved these changes
LGTM, one comment around testing happy to include it in a follow-up PR if you prefer.

2021-11-25 01:56 UTC, merged