Feat(web): password policy
authelia/authelia pull request #2723
Opened 2021-12-16 02:44 UTC by mind-ar

this PR implements an password metter in the "Reset Password" view
![imagen](https://user-images.githubusercontent.com/10672208/146298055-dcab31ed-a140-4c8e-91a4-c3a7204eb3ca.png)

this component works in two modes:
classic:
* the "metering" is performed using the basic rules (uppercase, lowercase, numbers, specials)
zxcvbn:
* uses the zxcvbn package to verify the password strength

related to https://github.com/authelia/authelia/issues/1631

2022-01-18 20:46 UTC, james-d-elliott commented
Thanks for the pr @mind-ar I will take a look at this as soon as I can, I got caught up with life!

2022-01-30 15:55 UTC, davama commented
This is great!
Thank you very much for adding this!!
@mind-ar is it possible to add `max_length` setting?

thanks!

2022-03-16 03:34 UTC, james-d-elliott requested changes
LGTM mostly, a few changes around language and one around the structure. Feel free to hold off on changing the configuration structure for now and let me see if one of the other maintainers can see if they agree with me.

2022-03-16 03:34 UTC, james-d-elliott commented on web/src/i18n/locales/en.json
> +        "Two long, maximum length is {{len}} letters": "Two long, maximum length is {{len}} letters"
```suggestion
        "The password does not meet the password policy": "The password does not meet the password policy",
        "Must have at least one lowercase letter": "Must have at least one lowercase letter",
        "Must have at least one UPPERCASE letter": "Must have at least one UPPERCASE letter",
        "Must have at least one number": "Must have at least one number",
        "Must have at least one special character": "Must have at least one special character",
        "Must be at least {{len}} characters in length": "Must be at least {{len}} characters in length",
        "Must not be more than {{len}} characters in length": "Must not be more than {{len}} characters in length"
```

2022-03-16 03:34 UTC, james-d-elliott commented on web/src/components/PasswordMeter.tsx
> +            setFeedback(warning);
```suggestion
            setFeedback(translate("The password does not meet the password policy") + ":\n" + warning);
```

See my other suggestions for why.

2022-03-16 03:34 UTC, james-d-elliott commented on web/src/components/PasswordMeter.tsx
> +                    warning += "* " + translate("Add some Special character") + "\n";
```suggestion
                    warning += "* " + translate("Must have at least one special character") + "\n";
```

2022-03-16 03:34 UTC, james-d-elliott commented on web/src/components/PasswordMeter.tsx
> +                    warning += "* " + translate("Add some Numbers") + "\n";
```suggestion
                    warning += "* " + translate("Must have at least one number") + "\n";
```

2022-03-16 03:34 UTC, james-d-elliott commented on web/src/components/PasswordMeter.tsx
> +                    warning += "* " + translate("Add some UPPERCASE letter") + "\n";
```suggestion
                    warning += "* " + translate("Must have at least one UPPERCASE letter") + "\n";
```

2022-03-16 03:34 UTC, james-d-elliott commented on web/src/components/PasswordMeter.tsx
> +                    warning += "* " + translate("Add some lowercase letter") + "\n";
```suggestion
                    warning += "* " + translate("Must have at least one lowercase letter") + "\n";
```

2022-03-16 03:34 UTC, james-d-elliott commented on web/src/components/PasswordMeter.tsx
> +                setFeedback(translate("Two long, maximum length is {{len}} letters", { len: props.maxLength }));
```suggestion
                setFeedback(translate("Must not be more than {{len}} characters in length", { len: props.maxLength }));
```

2022-03-16 03:34 UTC, james-d-elliott commented on web/src/components/PasswordMeter.tsx
> +                setFeedback(translate("Two short, minimun length is {{len}} letters", { len: props.minLength }));
```suggestion
                setFeedback(translate("Must be at least {{len}} characters in length", { len: props.minLength }));
```

2022-03-16 03:34 UTC, james-d-elliott commented on web/src/i18n/locales/en.json
> +        "Two long, maximum length is {{len}} letters": "Two long, maximum length is {{len}} letters"
Apply the same changes to es.

2022-03-16 12:14 UTC, mind-ar commented
Thanks @james-d-elliott , will apply suggested changes ASAP

2022-03-16 20:39 UTC, davama commented
@james-d-elliott @mind-ar 

Side note. Per my request which was kindly added: don't forget to add the max_lentgth in the documentation.

Thanks :bow:

2022-04-02 22:30 UTC, james-d-elliott approved these changes
LGTM

2022-04-02 22:32 UTC, merged