feat(authentication): custom reset password link
authelia/authelia pull request #2854
Opened 2022-02-07 11:13 UTC by you1996

feat(authentication): custom reset password URL

Administrators can now redirect users to their custom password reset portal and configure authelia to do so by disabling the internal password reset procedure and enabling the option to use an external portal in the case of some businesses who employ one.

Fixes https://github.com/authelia/authelia/issues/1934.

2022-03-16 04:15 UTC, james-d-elliott requested changes
So all looks fine to me. Just one suggestion around simplifying the configuration and something that will allow us to group other related options. I'll merge master into this branch and provide an example of how to utilize a URL struct in the config.

Edit: Seems I don't have permission to merge master into this. Please do so and you'll be able to use url.URL as in the configuration struct.

2022-03-16 04:15 UTC, james-d-elliott commented on docs/configuration/authentication/index.md
> +  external_reset_password_url: ""
```suggestion
  password_reset:
    custom_url: ""
```

2022-03-16 04:15 UTC, james-d-elliott commented on docs/configuration/authentication/index.md
> +The custom reset password URL, which redirects users to the custom reset password portal.
```suggestion
### password_reset

Password reset options. 

#### custom_url
<div markdown="1">
type: string
{: .label .label-config .label-purple } 
default: ""
{: .label .label-config .label-blue }
required: no
{: .label .label-config .label-green }
</div>

The custom reset password URL, which redirects users to the custom reset password portal. 
```

2022-03-16 04:15 UTC, james-d-elliott commented on internal/configuration/config.template.yml
> +
```suggestion
  ## Password Reset options.
  password_reset:
    ## Custom reset password url which replaces the internal password reset mechanism.
    custom_url: ""

```

2022-03-16 04:15 UTC, james-d-elliott commented on internal/configuration/validator/authentication.go
> +	}
```suggestion
	if configuration.PasswordReset.CustomURL.String() != "" && configuration.PasswordReset.CustomURL.Scheme != "https" && configuration.PasswordReset.CustomURL.Scheme != "http" {
		validator.Push(fmt.Errorf("Provided reset url is invalid. Error from parser: %s", err))
	}
```

2022-03-16 04:15 UTC, james-d-elliott commented on internal/configuration/validator/authentication.go
> +	}
I'll have to show an example of how to implement this in the schema.

2022-03-16 04:15 UTC, james-d-elliott commented on internal/server/server.go
> +	}
```suggestion
	externalResetURL := configuration.AuthenticationBackend.PasswordReset.CustomURL.String(
```

2022-03-16 04:15 UTC, james-d-elliott commented on internal/server/server.go
> +	serveSwaggerAPIHandler := ServeTemplatedFile(swaggerAssets, apiFile, configuration.Server.AssetPath, duoSelfEnrollment, rememberMe, resetPassword, externalResetPassword, externalResetURL, configurat
```suggestion
	serveIndexHandler := ServeTemplatedFile(embeddedAssets, indexFile, configuration.Server.AssetPath, duoSelfEnrollment, rememberMe, resetPassword, externalResetURL, configuration.Session.Name, configuration.Theme, https)
	serveSwaggerHandler := ServeTemplatedFile(swaggerAssets, indexFile, configuration.Server.AssetPath, duoSelfEnrollment, rememberMe, resetPassword, externalResetURL, configuration.Session.Name, configuration.Theme, https)
	serveSwaggerAPIHandler := ServeTemplatedFile(swaggerAssets, apiFile, configuration.Server.AssetPath, duoSelfEnrollment, rememberMe, resetPassword, externalResetURL, configuration.Session.Name, configuration.Theme, https)
```

2022-03-16 04:15 UTC, james-d-elliott commented on internal/server/template.go
> +func ServeTemplatedFile(publicDir, file, assetPath, duoSelfEnrollment, rememberMe, resetPassword, externalResetPassword, externalResetURL, session, theme string, https bool) middlewares.RequestHandle
```suggestion
func ServeTemplatedFile(publicDir, file, assetPath, duoSelfEnrollment, rememberMe, resetPassword, externalResetURL, session, theme string, https bool) middlewares.RequestHandler {
```

2022-03-16 04:15 UTC, james-d-elliott commented on internal/server/template.go
> +		err := tmpl.Execute(ctx.Response.BodyWriter(), struct{ Base, BaseURL, CSPNonce, DuoSelfEnrollment, LogoOverride, RememberMe, ResetPassword, ExternalResetPassword, ExternalResetURL, Session, Theme s
```suggestion
		err := tmpl.Execute(ctx.Response.BodyWriter(), struct{ Base, BaseURL, CSPNonce, DuoSelfEnrollment, LogoOverride, RememberMe, ResetPassword, ExternalResetURL, Session, Theme string }{Base: base, BaseURL: baseURL, CSPNonce: nonce, DuoSelfEnrollment: duoSelfEnrollment, LogoOverride: logoOverride, RememberMe: rememberMe, ResetPassword: resetPassword, ExternalResetURL: externalResetURL, Session: session, Theme: theme})
```

2022-03-16 04:15 UTC, james-d-elliott commented on web/index.html
> +        data-externalreseturl="%VITE_EXTERNAL_RESET_URL%"
```suggestion
        data-externalreseturl="%VITE_EXTERNAL_RESET_URL%"
```

2022-03-16 04:15 UTC, james-d-elliott commented on web/.env.production
> +VITE_EXTERNAL_RESET_URL={{.ExternalResetURL}}
```suggestion
VITE_EXTERNAL_RESET_URL={{.ExternalResetURL}}
```

2022-03-16 04:15 UTC, james-d-elliott commented on web/.env.development
> +VITE_EXTERNAL_RESET_URL=""
```suggestion
VITE_EXTERNAL_RESET_URL=""
```

2022-03-16 04:15 UTC, james-d-elliott commented on web/src/utils/Configuration.ts
> +}
```suggestion
export function getExternalResetPassword() {
    return getEmbeddedVariable("externalreseturl") !== "";
}

export function getExternalResetUrl() {
    return getEmbeddedVariable("externalreseturl");
}
```

2022-03-16 05:22 UTC, james-d-elliott requested changes

2022-03-16 05:22 UTC, james-d-elliott commented on internal/configuration/schema/authentication.go
>  }
```suggestion
	PasswordReset AuthenticationBackendPasswordResetConfiguration `koanf:"password_reset"`
	RefreshInterval             string                                  `koanf:"refresh_interval"`
	LDAP                        *LDAPAuthenticationBackendConfiguration `koanf:"ldap"`
	File                        *FileAuthenticationBackendConfiguration `koanf:"file"`
}

// AuthenticationBackendPasswordResetConfiguration holds password reset information.
type AuthenticationBackendPasswordResetConfiguration struct {
	CustomURL *url.URL                                  `koanf:"custom_url"`
}
```

2022-03-16 11:11 UTC, you1996 commented
> So all looks fine to me. Just one suggestion around simplifying the configuration and something that will allow us to group other related options. I'll merge master into this branch and provide an example of how to utilize a URL struct in the config.
> 
> Edit: Seems I don't have permission to merge master into this. Please do so and you'll be able to use url.URL as in the configuration struct.

Hello james, thank you for the review, merge done.

2022-03-16 11:25 UTC, james-d-elliott commented
> > So all looks fine to me. Just one suggestion around simplifying the configuration and something that will allow us to group other related options. I'll merge master into this branch and provide an example of how to utilize a URL struct in the config.
> > Edit: Seems I don't have permission to merge master into this. Please do so and you'll be able to use url.URL as in the configuration struct.
> 
> Hello james, thank you for the review, merge done.

Nice one! You'll have to change the references in the validator from `configuration` to `config`. We shortened it since the additional `uration` was superfluous.

2022-03-30 22:21 UTC, james-d-elliott commented
Did you get around to those fixes? Once I merge all the other 4.35.0 images I am hoping this is ready or I'll have to fix it up myself.

I'd appreciate if I can push to this branch if you don't have time to fix this up, though I can manually takeover this PR worst case scenario, you can enable this by clicking this checkbox:

![image](https://user-images.githubusercontent.com/3903683/160940583-dc3e767a-367c-43ee-9293-9bd7708c82c9.png)

2022-04-04 07:46 UTC, closed without merging