Add i18n-de
authelia/authelia pull request #3043
Opened 2022-03-20 16:41 UTC by protvis74

Added German translation to Authelia.

2022-03-20 21:24 UTC, james-d-elliott requested changes

2022-03-20 21:24 UTC, james-d-elliott commented on index.ts
> +export default i18n;
Modify the existing index.ts, don't add a new one.

2022-03-20 22:22 UTC, protvis74 commented
Modified the existing index.ts as requested.

2022-03-20 23:35 UTC, james-d-elliott approved these changes
LGTM

2022-04-01 10:25 UTC, merged

2022-04-02 04:18 UTC, james-d-elliott commented
@all-contributors please add @protvis74 for translation

2022-05-16 02:11 UTC, james-d-elliott commented
@protvis74 I'm formally inviting you to crowdin if you want to translate any missing translations or review any suggestions: https://crwd.in/authelia