feat: envoy support
authelia/authelia pull request #3793
Opened 2022-08-06 02:09 UTC by james-d-elliott

This effectively adds support for [envoy](https://www.envoyproxy.io/). Docs to come.

2022-08-06 03:33 UTC, nightah approved these changes
LGTM, great work with this!

2022-08-06 05:01 UTC, james-d-elliott commented
> LGTM, great work with this!

Likewise, we knocked this out so damn quickly. Really helps to have a few sets of eyes.

2022-09-25 23:12 UTC, nightah requested changes
Looks like we left a couple debug log lines in since we were trying to fix this.

2022-09-25 23:12 UTC, nightah commented on internal/handlers/handler_verify.go
> +
```suggestion
```

Did we have these in just to debug, I suspect they need to be removed.

2022-09-25 23:12 UTC, nightah commented on internal/utils/url.go
> +
```suggestion
```

I suspect the same as the previous suggestion.

2022-09-26 00:40 UTC, nightah approved these changes
LGTM.

2022-10-01 11:47 UTC, merged