docs: update Seafile OIDC integration
authelia/authelia pull request #4151
Opened 2022-10-08 21:48 UTC by philwilei

I recently used this guide to integrate my Seafile with my Authelia. I ran into a couple issues along the way and updated the docs accordingly:
* Remove the `groups` scope from the Seafile config since Seafile doesn't use this information (as far as I can tell) and the given Authelia config doesn't even grant this scope.
* Fix the `OAUTH_ATTRIBUTE_MAP` in the Seafile config. When using the old values Seafile was reporting "Required user info not found" and login would fail.
* Update the tested versions.
* Add a note regarding an issue with the provided configuration and hints on how to mitigate. Also add a step for installing a required pip package.
* Reference the sources that helped me fix the issues I had.

2022-10-09 05:10 UTC, james-d-elliott requested changes
Thanks for choosing to contribute! I really appreciate it. I understand the motivation but I think most of this should be part of the Seafile documentation not our documentation.

Can you check if the removal of the `id` line in the OAUTH_ATTRIBUTE_MAP works and let me know? In addition I've included several changes which remove sections that should be part of the Seafile docs.

2022-10-09 05:10 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/seafile/index.md
> +
```suggestion
```

2022-10-09 05:10 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/seafile/index.md
> +    "id": (False, "not used"),
```suggestion
```

2022-10-09 05:10 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/seafile/index.md
> +1. Install the `requests_oauthlib` pip package which is required but not installed with [Seafile] by default[^3].
```suggestion
1. Install `requests_oauthlib` which is required but not installed with [Seafile] by default. See the [Seafile] documentation in the [see also](#see-also) section for more information.
```

2022-10-09 05:10 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/seafile/index.md
> +
```suggestion
```

2022-10-09 05:10 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/seafile/index.md
> +
```suggestion
```

2022-10-09 14:11 UTC, philwilei commented
Thanks for the prompt feedback on my PR.  I experimented with removing the `id` mapping, however Seafile sets a default value which causes authentication to break when I don't overwrite it. There may be a better solution, but I am no OAuth expert and the Seafile docs [suggest](https://manual.seafile.com/deploy/oauth/#__code_6) doing it this way so I would consider it acceptable.

2022-10-09 19:17 UTC, james-d-elliott commented
> Thanks for the prompt feedback on my PR. I experimented with removing the `id` mapping, however Seafile sets a default value which causes authentication to break when I don't overwrite it. There may be a better solution, but I am no OAuth expert and the Seafile docs [suggest](https://manual.seafile.com/deploy/oauth/#__code_6) doing it this way so I would consider it acceptable.

Yep perfect, that's the feedback I was after. Pitty they're not more explicit about it.

2022-10-10 01:08 UTC, james-d-elliott approved these changes
LGTM!

2022-10-18 10:27 UTC, merged