feat(server): custom html page for `form_post` response method
authelia/authelia pull request #4670
Opened 2022-12-31 19:46 UTC by levkoburburas

This pull request solves two issues:

1. Applies [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) to the html page used as the form_post response method, see related issue [#4669](https://github.com/authelia/authelia/issues/4669).
2. Customize oidc authorization page.  

![Redirecting to Bitwarden Password Manager - Authelia 2022-12-31 at 8 54 38 PM](https://user-images.githubusercontent.com/62853952/210154282-81571558-fc7a-4073-8f0b-83e6172740c2.jpg)

2022-12-31 21:18 UTC, james-d-elliott requested changes
Thanks for the PR. However I'd rather this is solved by adjusting the template returned from `fosite.FormPostHTMLTemplateProvider` using sha256 hashes instead (in addition to making a special CSP middleware for the authorization endpoint which adds the sha256's when the response mode is `form_post`).

2022-12-31 23:31 UTC, levkoburburas commented
> Thanks for the PR. However I'd rather this is solved by adjusting the template returned from `fosite.FormPostHTMLTemplateProvider` using sha256 hashes instead (in addition to making a special CSP middleware for the authorization endpoint which adds the sha256's when the response mode is `form_post`).


Thank you for the review!

This could be a great solution, if only this approach also supported passing variables. It is important for me to display the clientID/clientDescription, in fact, where the redirect goes.

I will try to make code changes in `fosite`, if they accept them, I will redo this PR, otherwise this approach is preferable for me.

2022-12-31 23:42 UTC, james-d-elliott commented
I don't think it's necessary to implement the client description in the short term. However I'm relatively certain they'd be open to implementing an interface addition to the configurator with a signature similar to below:

```go
type AuthorizeFormPostResponseProvider interface {
    GetWriteAuthorizeFormPostResponse(ctx context.Context) func(redirectURL string, parameters url.Values, template *template.Template, rw io.Writer)
}
```

2023-01-01 01:46 UTC, levkoburburas commented
I liked your first suggestion, because it seems to me that it gives more opportunities

```go
type FormPostResponseProvider interface {
    GetWriteFormPostResponse(ctx context.Context) func(rw io.Writer, template *template.Template, redirectURL string, parameters url.Values)
}
```

I created the PR [#731](https://github.com/ory/fosite/pull/731) with discussed changes.

> If you'd like I can just push the fix and you can work on the nice to have, I'll leave it up to you however.

Thank you, but it's up to you. I work with forked repo, it doesn't bother me.

2023-01-01 01:50 UTC, levkoburburas commented
By the way, I'm not very good at frontend, perhaps you should that page it and improve something at your discretion.

2025-03-11 22:27 UTC, james-d-elliott commented
We've moved to our own fork of fosite, so we can probably fix this up in a cleaner way. Was thinking of doing this for 4.39 but it seems too far diverged. Let me know if you're still interested in a custom form post page.

2025-03-11 22:27 UTC, closed without merging