test(suites): load environment into suites
authelia/authelia pull request #4762
Opened 2023-01-13 04:11 UTC by james-d-elliott

2023-01-23 09:52 UTC, nightah requested changes
Couple of small changes.

Also I noticed the following:
* BypassAll, DuoPush, HighAvailability, Standalone suites all seem to run the load of env vars two or more times, probably because of the underlying scenario suites, we should prevent this.

* The following test seemed to error, not sure if that's related to this change or not:
```
=== RUN   TestOIDCSuite/TestOIDCScenario/TestShouldDenyConsent/error_uri
    verify_is_oidc.go:28: Test Skipped as the element is not expected.
```

2023-01-23 09:52 UTC, nightah commented on internal/suites/suite_network_acl_test.go
> +			Name: traefikSuiteName,
```suggestion
			Name: networkACLSuiteName,
```

2023-01-23 09:52 UTC, nightah commented on internal/suites/utils.go
> +	fmt.Printf("Checking Suite %s for .env file\n", s.Name)
Can we change all the logging here to be debug?

2023-01-23 10:15 UTC, james-d-elliott commented
> * The following test seemed to error, not sure if that's related to this change or not:

Yeah this was because that suite checks the responses in a recursive way, the skip is for when the error is not expected.

> * BypassAll, DuoPush, HighAvailability, Standalone suites all seem to run the load of env vars two or more times, probably because of the underlying scenario suites, we should prevent this.

Do we want to maybe convert all of them into a single suite?

2023-01-25 04:04 UTC, nightah approved these changes
LGTM.

2023-01-25 04:11 UTC, merged