Documentation for Kasm Workspaces OpenID 1.0
authelia/authelia pull request #5314
Opened 2023-04-25 21:46 UTC by HaroldVB

I created a documentation for a Kasm Workspaces Open ID 1.0 connection. This is working in my configuration, if you have any questions please feel free to contact me.

2023-04-25 22:59 UTC, james-d-elliott requested changes
Few changes. One is a fix, and two are consistency changes.

2023-04-25 22:59 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/kasm-workspaces/index.md
> +        secret: 'insecure-secret'
```suggestion
        secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'  # The digest of 'insecure_secret'.
      public: false
```

2023-04-25 22:59 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/kasm-workspaces/index.md
> +* __Application Root URL:__ `https://kasm.example.com`
```suggestion
* __Application Root URL:__ `https://kasm.example.com`
* __Authelia Root URL:__ `https://auth.example.com`
```

2023-04-25 22:59 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/kasm-workspaces/index.md
> +parent: "openid-connect"
```suggestion
menu:
  integration:
    parent: "openid-connect"

```

2023-04-26 04:44 UTC, HaroldVB commented
Hi! No problem, wanted to make my first open-source contribution. I commit your changes to the pull request, thank you for noticing.

2023-04-26 08:46 UTC, james-d-elliott commented
> May I ask why you deleted, authorization, token and userinfo URL? It's listed that way in the Portainer integration too, thought it was easy to copy and paste without needing to google it again. Makes it easier to find the correct information for the user.
> 
> I propose we put them back.

Because the general format of the assumptions are the key parts of the following instructions that will very likely change, you can include them but they should be in the [application configuration section](https://www.authelia.com/integration/openid-connect/portainer/#application), not the [assumptions section](https://www.authelia.com/integration/openid-connect/portainer/#assumptions). The consistency is the key with this.

2023-04-26 08:48 UTC, james-d-elliott requested changes
I screwed this one up in my suggestion, whoops!

2023-04-26 08:48 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/kasm-workspaces/index.md
> +        public: false
```suggestion
        secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'  # The digest of 'insecure_secret'.
        public: false
```

2023-04-27 06:42 UTC, HaroldVB commented
Hm, pr still open after merge, looks like some checks failed.

2023-04-27 08:37 UTC, james-d-elliott approved these changes

2023-04-27 08:37 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/kasm-workspaces/index.md
> +![Kasm](kasm.png)
```suggestion
{{< figure src="kasm.png" alt="Kasam Workspaces" width="736" style="padding-right: 10px" >}}
```

2023-04-27 08:40 UTC, merged

2023-04-27 08:40 UTC, james-d-elliott commented
@all-contributors please add @HaroldVB for docs