docs: update caddy subpath example, fix spelling issues
authelia/authelia pull request #5661
Opened 2023-07-10 05:04 UTC by tzfx

As referenced in discussion #5660 

Thought it would be helpful for users to have a heads-up that they need to update their `server.address` configuration in order to make the caddy subpath example work.

Without it, the portal fails to render as it tries to pull javascript and css files from the wrong base path.

I also noticed some minor spelling issues that were copypasta'd across the proxies markdown files.

2023-07-10 06:26 UTC, james-d-elliott requested changes
The following changes will prevent us having to maintain additional areas of the docs unnecessarily. I'm also wondering why we don't have subpath config examples for other providers but do so for Caddy. Considering the idea of removing the subpath proxy configuration examples entirely.

2023-07-10 06:26 UTC, james-d-elliott commented on docs/content/en/integration/proxies/caddy.md
> +```
```suggestion
```

2023-07-10 06:26 UTC, james-d-elliott commented on docs/content/en/integration/proxies/caddy.md
> +[server address configuration](../../configuration/miscellaneous/server.md#address) to listen on the new endpoint:*
```suggestion
[server address configuration](../../configuration/miscellaneous/server.md#address) to listen on the new endpoint.*
```

2023-07-12 02:06 UTC, tzfx commented on docs/content/en/integration/proxies/caddy.md
> +[server address configuration](../../configuration/miscellaneous/server.md#address) to listen on the new endpoint:*
Updated latest commit with suggested changes.

2023-07-12 02:12 UTC, tzfx commented
>  Considering the idea of removing the subpath proxy configuration examples entirely.

My own selfish self really likes that a subpath config was included-- It worked perfectly (once I understood what was going on) for my use case in a way that didn't have me jumping through hoops with my dynamic dns provider on their free-tier. :)

2023-07-19 01:19 UTC, merged