Fixes an error caused by not providing an optional port value
authelia/authelia pull request #5853
Opened 2023-08-16 04:45 UTC by paulcalabro

2023-08-16 05:51 UTC, james-d-elliott requested changes

2023-08-16 05:51 UTC, james-d-elliott commented on internal/configuration/validator/session.go
> +		config.Redis.Port = 26379
This should be the correct redis default port which is 6379, not 26379. Also this should utilize the schema.DefaultRedisConfiguration as the value should be set and used from there..

2023-08-16 05:51 UTC, james-d-elliott commented on internal/configuration/validator/session_test.go
> -	assert.EqualError(t, validator.Errors()[0], "session: redis: option 'port' must be between 1 and 65535 but it's configured as '0'")
This change likely reduces coverage. Please revert it and correct the test scenario / conditions so the test passes.

2023-08-16 05:51 UTC, james-d-elliott commented on internal/configuration/validator/session_test.go
> +	assert.Equal(t, 26379, config.Redis.Port)
Please add a separate test for this (unless there is already one testing default values).

2023-08-17 22:05 UTC, paulcalabro commented
@james-d-elliott Does that look okay?

2023-08-18 10:35 UTC, james-d-elliott approved these changes
LGTM

2023-08-18 11:48 UTC, merged