Documentation :  add powerdns oid integration
authelia/authelia pull request #6491
Opened 2024-01-02 23:46 UTC by Kitof

2024-01-03 04:55 UTC, james-d-elliott requested changes
Few changes otherwise LGTM. Wouldn't happen to know what client auth mechanism they use would you?

2024-01-03 04:55 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/powerdns/index.md
> +  - /docs/community/oidc-integrations/powerdns.html
```suggestion
```

2024-01-03 04:55 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/powerdns/index.md
> +          - authorization_code
```suggestion
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://powerdns.example.com/oidc/authorized'
        scopes:
          - ''openid'
          - 'profile'
          - 'groups'
          - 'email'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
```

2024-01-03 04:55 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/powerdns/index.md
> +        description: PowerDNS
```suggestion
      - id: 'powerdns'
        description: 'PowerDNS'
```

2024-01-03 09:23 UTC, Kitof commented on docs/content/en/integration/openid-connect/powerdns/index.md
> +          - authorization_code
Be careful : double quote on ''openid'

2024-01-15 21:45 UTC, james-d-elliott approved these changes
LGTM just making this one change.

2024-01-15 21:45 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/powerdns/index.md
> +  * [v0.4.1]([https://github.com/PowerDNS-Admin/PowerDNS-Admin](https://github.com/PowerDNS-Admin/PowerDNS-Admin/releases/tag/v0.4.1))
```suggestion
  * [v0.4.1](https://github.com/PowerDNS-Admin/PowerDNS-Admin/releases/tag/v0.4.1)
```

2024-01-15 21:47 UTC, merged