docs(oidc): add freshrss oidc integration guide
authelia/authelia pull request #6688
Opened 2024-02-14 23:13 UTC by darkpixelftw

Create integration guide for oidc authentication for freshrss and authelia

Document non-obvious behaviour that freshrss expects port in the redirect URI

Signed-off-by: darkpixelftw <darkpixelftw@outlook.com>

2024-02-14 23:30 UTC, james-d-elliott commented
Really appreciate the contribution! If you have time I'd appreciate confirming the token endpoint auth method this client uses. We will likely be requiring this to be configured in authelia in the next release.

2024-02-15 19:49 UTC, darkpixelftw commented
Hi, I asked the maintainer of FreshRSS what the token auth method is and it seems we're having a bit of trouble answering this, see: https://github.com/FreshRSS/FreshRSS/issues/6102

2024-02-15 21:24 UTC, james-d-elliott commented
Thanks, it's `client_secret_basic`. I'll make the recommendations based on this.

2024-02-15 21:59 UTC, james-d-elliott requested changes
Thanks so much for contributing! Just a few changes. I know you've not tested with v4.38.0 but we're only accepting PR's with this version in mind as we're pretty close to a release.

If you'd like to verify this I can probably help you. Otherwise we can wait for the release and you can reevaluate.

2024-02-15 21:59 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/freshrss/index.md
> +  * [v4.37.5](https://github.com/authelia/authelia/releases/tag/v4.37.5)
```suggestion
  * [v4.38.0](https://github.com/authelia/authelia/releases/tag/v4.38.0)
```

2024-02-15 21:59 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/freshrss/index.md
> +      userinfo_signed_response_alg: 'none'
```suggestion
      token_endpoint_auth_method: 'client_secret_post'
      userinfo_signed_response_alg: 'none'
```

2024-02-15 21:59 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/freshrss/index.md
> +        - profile
```suggestion
        - 'openid'
        - 'groups'
        - 'email'
        - 'profile'
```

2024-02-15 21:59 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/freshrss/index.md
> +        - https://freshrss.example.com:443/i/oidc/ # IMPORTANT: you must add the port to the redirect uri
```suggestion
        - 'https://freshrss.example.com:443/i/oidc/'
```

2024-02-15 21:59 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/freshrss/index.md
> +      authorization_policy: two_factor
```suggestion
      authorization_policy: 'two_factor'
```

2024-02-15 21:59 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/freshrss/index.md
> +      description: freshrss
```suggestion
    - id: 'freshrss'
      description: 'freshrss'
```

2024-02-15 21:59 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/freshrss/index.md
> +
```suggestion

### Special Notes

1. The FressRSS implementation seems to always include the port in the requested `redirect_uri`. As Authelia strictly conforms to the specifications this means the client registration **_MUST_** include the port for the requested `redirect_uri` to match.

```

2024-02-16 10:20 UTC, darkpixelftw commented
> Thanks so much for contributing! Just a few changes. I know you've not tested with v4.38.0 but we're only accepting PR's with this version in mind as we're pretty close to a release.
> 
> If you'd like to verify this I can probably help you. Otherwise we can wait for the release and you can reevaluate.

Sure it would be a great help if you could verify it on the 4.38 version, If not then I'll just wait for the release. Is there an ETA for when the next release is?

2024-02-18 10:46 UTC, james-d-elliott requested changes

2024-02-18 10:46 UTC, james-d-elliott commented on docs/content/en/integration/openid-connect/freshrss/index.md
> +      token_endpoint_auth_method: 'client_secret_post'
```suggestion
      token_endpoint_auth_method: 'client_secret_basic'
```

2024-02-18 10:47 UTC, james-d-elliott commented
We don't have a specific ETA, but it should be soon. We can try it against the beta but you'll need a database backup.

2024-03-05 10:56 UTC, merged