feat: passkeys
authelia/authelia pull request #7942
Opened 2024-09-29 01:48 UTC by james-d-elliott

Add support for passkeys, granular attachment modality, and granular authenticator selection. This also adds metadata verification elements utilizing the MDS3 to the project, including saving attestation statements, verification of attestation statements, etc. This also makes a significant change to the authentication level logic to purely use authentication method references to ensure the future-proof nature of the implementation. It should be noted that at the time of this commit Passkey authentication is considered a single factor and we will at a later stage add more customizable policies to allow configuring the requirements for a specific authentication level on a per rule basis using a custom 'policy' that administrators can define.

2025-01-03 06:50 UTC, Crowley723 submitted a review, later dismissed

2025-01-03 06:50 UTC, Crowley723 commented on internal/handlers/handler_sign_password.go
> +// SecondFactorPasswordPOST is the handler performing the first factory.
```suggestion
// SecondFactorPasswordPOST is the handler performing the first factor.
```

2025-01-04 10:43 UTC, james-d-elliott commented on internal/commands/const.go
> +	cmdAutheliaStorageCacheMDS3DumpShort = "Dump WebAuthn MDS3 cache storage"
All of the consts in this file with the Short suffix must be single line which is why we use this format.

2025-02-17 04:22 UTC, nightah requested changes
Mostly LGTM, few suggestions and nits.

2025-02-17 04:22 UTC, nightah commented on internal/suites/scenario_one_factor_test.go
> +	suite.Run(t, NewOneFactorScenario())
This was named `1FA` instead of `OneFactor` to ensure ordering, if it was a nit I would likely just revert the majority of this change (happy to change Suite -> Scenario).

2025-02-17 04:22 UTC, nightah commented on internal/suites/scenario_two_factor_totp_test.go
> +	suite.Run(t, NewTwoFactorTOTPScenario())
This name should also be retained for ordering.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_activedirectory_test.go
> +func (s *ActiveDirectorySuite) TestOneFactorScenario() {
This file should be reverted.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_caddy_test.go
> +func (s *CaddySuite) TestOneFactorScenario() {
This file should be reverted.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_docker_test.go
> +func (s *DockerSuite) TestOneFactorScenario() {
This file should be reverted.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_envoy_test.go
> +func (s *EnvoySuite) TestOneFactorScenario() {
This file should be reverted.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_haproxy_test.go
> +func (s *HAProxySuite) TestOneFactorScenario() {
This file should be reverted.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_high_availability_test.go
> +func (s *HighAvailabilitySuite) TestOneFactorScenario() {
This file should be reverted.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_kubernetes_test.go
> +func (s *KubernetesSuite) TestOneFactorScenario() {
This file should be reverted.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_ldap_test.go
> +func (s *LDAPSuite) TestOneFactorScenario() {
This file should be reverted.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_mariadb_test.go
> +func (s *MariaDBSuite) TestOneFactorScenario() {
This file should be reverted.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_mysql_test.go
> +func (s *MySQLSuite) TestOneFactorScenario() {
This file should be reverted.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_pathprefix_test.go
> +func (s *PathPrefixSuite) TestOneFactorScenario() {
This file should be reverted.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_postgres_test.go
> +func (s *PostgresSuite) TestOneFactorScenario() {
This file should be reverted.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_standalone_test.go
> +func (s *StandaloneSuite) TestOneFactorScenario() {
This file should be reverted.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_traefik_test.go
> +func (s *TraefikSuite) TestOneFactorScenario() {
This file should be reverted.

2025-02-17 04:22 UTC, nightah commented on internal/suites/suite_two_factor_test.go
> +func (s *TwoFactorSuite) TestNewTwoFactorOneTimePasswordScenario() {
This file will need to be adapted to the reverted changes.

2025-02-17 04:22 UTC, nightah commented on internal/webauthn/credential.go
> +	}
Is it worth unit testing these expected cases?

2025-02-18 07:24 UTC, Crowley723 reviewed
Looks good to me other than a couple questions.

2025-02-18 07:24 UTC, Crowley723 commented on docs/content/configuration/second-factor/webauthn.md
> +    discoverability: 'discouraged'
nitpick: 
```suggestion
    discoverability: 'preferred'
```
Since the default value for discoverability is 'preferred' do we want to have it set as that here or is that not important?

2025-02-22 23:53 UTC, james-d-elliott commented on internal/configuration/const.go
> +	mapDefaults = map[string]any{
It's going to be used in this release cycle, I can't recall what for, plus I think it'd be confusing to look at later.

2025-02-22 23:54 UTC, james-d-elliott commented on internal/configuration/test_resources/config.webauthn-defaults.yml
> +  #   user_verification: ''
No, it was just to test the effects of empty strings to ensure it's working as expected.

2025-02-23 00:21 UTC, james-d-elliott commented on docs/static/schemas/v4.39/json-schema/configuration.json
> -          "default": "Authelia Test \u003ctest@authelia.com\u003e"
I don't think it was ever implemented properly for this struct, pretty sure I fluked getting it working at some stage and broke it again accidentally.

2025-02-23 00:21 UTC, james-d-elliott commented on internal/regulation/const.go
> +	// AuthTypePassword is the string representing an auth log for second-factor authentication via a Password.
It's only used for password after passkey at the moment. `1FA` is used for traditional 1FA.

2025-02-23 01:22 UTC, james-d-elliott commented on internal/handlers/response.go
> -func Handle1FAResponse(ctx *middlewares.AutheliaCtx, targetURI, requestMethod string, username string, groups []string) {
It's just a standard way arguments with repeated types are represented.

2025-02-23 03:59 UTC, james-d-elliott commented on docs/content/configuration/second-factor/webauthn.md
> +    discoverability: 'discouraged'
Implemented and also changed the attachment to any.

2025-02-23 03:59 UTC, james-d-elliott commented on internal/webauthn/credential.go
> +	}
Yeah that's why I extracted this instead of leaving it in the commands package, done.

2025-02-23 05:08 UTC, merged

2025-02-23 06:42 UTC, ishanjain28 commented
Yay! 🎉 Thank you!

2025-02-23 12:30 UTC, archef2000 commented
Thank you for all the work.