test(suites): traefik3
authelia/authelia pull request #8032
Opened 2024-10-15 03:16 UTC by james-d-elliott

2024-10-15 05:20 UTC, james-d-elliott commented on internal/suites/example/compose/nginx/backend/docker-compose.yml
> +      - 'traefik.http.routers.protectedapps.rule=Host(`admin.example.com`) || Host(`deny.example.com`) || Host(`home.example.com`) || Host(`public.example.com`) || Host(`secure.example.com`) || Host(
Fix required for Traefik3

2024-10-15 05:20 UTC, james-d-elliott commented on internal/suites/suite_traefik2_test.go
> +	suite.Run(t, NewTraefikSuite(traefik2SuiteName))
This is expected, the Test itself needs to be named like this.

2024-10-15 05:20 UTC, james-d-elliott commented on internal/suites/Traefik/configuration.yml
> +identity_validation:
The changes in this file are effectively a move from Traefik2 -> Traefik

2024-10-15 05:20 UTC, james-d-elliott commented on internal/suites/Traefik/docker-compose.yml
> +      - './Traefik/favicon.ico:/config/assets/favicon.ico'
Added due to the rename from Traefik2 -> Traefik, see the below renames.

2024-10-15 05:20 UTC, james-d-elliott commented on internal/suites/example/compose/oidc-client/docker-compose.yml
> +      - 'traefik.http.routers.oidc.priority=1000'
Fix required for the Traefik3 fix above.

2024-10-16 23:10 UTC, Crowley723 commented on internal/suites/Traefik/users.yml
At least one hash has changed from default and the yamllint exception was removed.
Was that intended?

2024-10-17 00:29 UTC, Crowley723 requested changes
I agree with the grammar changes and I think we should try to keep the user.yml files the same. Otherwise it looks good.

2024-10-17 00:29 UTC, Crowley723 commented on internal/suites/Traefik/users.yml
> +        disabled: false
Lets keep the users.yml standard.
```suggestion
  john:
    displayname: "John Doe"
    password: "$6$rounds=500000$jgiCMRyGXzoqpxS3$w2pJeZnnH8bwW3zzvoMWtTRfQYsHbWbD/hquuQ5vUeIyl9gdwBIt6RWk2S6afBA0DPakbeWgD/4SZPiS0hYtU/"  # yamllint disable-line rule:line-length
    email: john.doe@authelia.com
    groups:
      - admins
      - dev

  harry:
    displayname: "Harry Potter"
    password: "$6$rounds=500000$jgiCMRyGXzoqpxS3$w2pJeZnnH8bwW3zzvoMWtTRfQYsHbWbD/hquuQ5vUeIyl9gdwBIt6RWk2S6afBA0DPakbeWgD/4SZPiS0hYtU/"  # yamllint disable-line rule:line-length
    email: harry.potter@authelia.com
    groups: []

  bob:
    displayname: "Bob Dylan"
    password: "$6$rounds=500000$jgiCMRyGXzoqpxS3$w2pJeZnnH8bwW3zzvoMWtTRfQYsHbWbD/hquuQ5vUeIyl9gdwBIt6RWk2S6afBA0DPakbeWgD/4SZPiS0hYtU/"  # yamllint disable-line rule:line-length
    email: bob.dylan@authelia.com
    groups:
      - dev

  james:
    displayname: "James Dean"
    password: "$6$rounds=500000$jgiCMRyGXzoqpxS3$w2pJeZnnH8bwW3zzvoMWtTRfQYsHbWbD/hquuQ5vUeIyl9gdwBIt6RWk2S6afBA0DPakbeWgD/4SZPiS0hYtU/"  # yamllint disable-line rule:line-length
    email: james.dean@authelia.com
...

```

2024-10-17 00:29 UTC, Crowley723 commented on internal/suites/Traefik/users.yml
>  users:
```suggestion
---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
```

2024-10-18 00:35 UTC, Crowley723 approved these changes

2024-10-18 00:57 UTC, merged