feat(configuration): reusable definitions
authelia/authelia pull request #8077
Opened 2024-10-21 23:46 UTC by james-d-elliott

This adds reusable definitions into the mix for the configuration. This replaces the existing networks section for the access_control section and is automatically remapped for users.

2024-10-22 06:23 UTC, Crowley723 reviewed
It looks good to me, a couple nit picks.

Should 0.0.0.0/0 be an allowable IP for a network definition? How would it (or ipv6 equivalent) be handled by the rule parser?

2024-10-22 06:23 UTC, Crowley723 commented on internal/configuration/provider.go
> +			val.Push(fmt.Errorf("error occurred during unmarshalling definitions configuration: the definition for network with name '%s' exists in both the defintions section and access control section which
^

2024-10-22 06:23 UTC, Crowley723 commented on internal/configuration/provider_test.go
Should `0.0.0.0/0` be an allowable IP? 
Its correct CIDR but would match any network (maybe not) which is the same as not including networks.
May or may not be worth it to include as a test case.

2024-10-22 06:23 UTC, Crowley723 commented on internal/utils/ip.go
Should 0.0.0.0/0 be allowable?

2024-10-22 06:23 UTC, Crowley723 commented on internal/utils/ip_test.go
Add 0.0.0.0/0 as test case if it shouldn't be a valid ip.

2025-01-04 13:18 UTC, james-d-elliott commented
@coderabbitai please review this again

2025-02-16 22:15 UTC, nightah approved these changes
LGTM, tiny nit which you can choose to include at your leisure.

2025-02-16 22:15 UTC, nightah commented on internal/configuration/decode_hooks.go
> +}
Small nit here, you can choose to accept or deny this.

```suggestion
func StringToIPNetworksHookFunc(definitions map[string][]*net.IPNet) mapstructure.DecodeHookFuncType {
	return func(f reflect.Type, t reflect.Type, data any) (value any, err error) {
		expectedType := reflect.TypeOf(net.IPNet{})

		if f.Kind() != reflect.String && (f.Kind() != reflect.Slice || (f.Elem().Kind() != reflect.Interface && f.Elem().Kind() != reflect.String)) {
			return data, nil
		}

		isSlice := t.Kind() == reflect.Slice && t.Elem().Kind() == reflect.Ptr && t.Elem().Elem() == expectedType
		isKind := t.Kind() == reflect.Ptr && t.Elem() == expectedType

		if !isSlice && !isKind {
			return data, nil
		}

		var values []string
		switch d := data.(type) {
		case string:
			values = []string{d}
		case []string:
			values = d
		case []any:
			values = make([]string, len(d))
			for i, v := range d {
				values[i] = fmt.Sprint(v)
			}
		default:
			return data, nil
		}

		var networks []*net.IPNet

		for _, str := range values {
			if definition, ok := definitions[str]; ok {
				networks = append(networks, definition...)

				continue
			}

			network, err := utils.ParseHostCIDR(str)
			if err != nil {
				return nil, fmt.Errorf("failed to parse network %q: %w", str, err)
			}

			networks = append(networks, network)
		}

		return networks, nil
	}
}
```

2025-02-18 07:03 UTC, Crowley723 requested changes
Some minor suggestions, otherwise it looks good to me.

2025-02-18 07:03 UTC, Crowley723 commented on internal/utils/ip_test.go
> +		},
```suggestion
		},
		{
                    "ShouldNotParseEmptyString",
                    "",
                    nil,
                    "invalid CIDR address: ",
		},
		{
                    "ShouldNotParseInvalidIPv4Format",
                    "256.256.256.256",
                    nil,
                    "invalid CIDR address: 256.256.256.256",
                },
                {
                    "ShouldNotParseIPv4IncompleteOctets",
                    "192.168.1",
                    nil,
                    "invalid CIDR address: 192.168.1",
                },
                {
                    "ShouldNotParseIPv6InvalidCIDR",
                    "2001:db8::1/129",
                    nil,
                    "invalid CIDR address: 2001:db8::1/129",
                },
                {
                    "ShouldNotParseIPv4InvalidCIDR",
                    "192.168.1.1/33",
                    nil,
                    "invalid CIDR address: 192.168.1.1/33",
                },
```
Just some potential edge cases we might want to verify.

2025-02-18 07:13 UTC, james-d-elliott commented on internal/configuration/validator/identity_providers.go
> +			if !IsSubjectValidBasic(subject) {
The function correctly describes what we're doing, we are checking if a subject is valid in a basic way, i.e. non-comprehensively.

2025-02-18 07:14 UTC, james-d-elliott commented on internal/configuration/test_resources/decode_networks.yml
> +      - '192.168.2.0/24'
It'd be treated as /32 since the user has not specified and there is no way to automatically determine an intended mask from just an IP.

2025-02-18 07:17 UTC, james-d-elliott commented on internal/utils/ip_test.go
> +		},
Always a /32 or /128 if there is no CIDR notation mask.

2025-02-18 08:57 UTC, james-d-elliott commented on internal/utils/ip_test.go
> +		},
Added locally.

2025-02-18 09:38 UTC, merged