docs: update gmail example
authelia/authelia pull request #8162
Opened 2024-11-04 10:50 UTC by hendrik1120

Hi,

this updates the Gmail example to use the new address scheme.
The reference to [security] was also missing. I hope I linked it as intended.

2024-11-04 18:33 UTC, Crowley723 submitted a review, later dismissed
LGTM but lets remove the (broken) link to `#notifier-security-measures-smtp`

2024-11-04 18:33 UTC, Crowley723 commented on docs/content/configuration/notifications/smtp.md
> +[security]: ../../overview/security/measures.md#notifier-security-measures-smtp
It doesn't look like this renders correctly. 
I don't think that its a good idea to clutter the configuration reference page with miscellaneous information. 
Some people are saying that our site is cluttered with information that makes it hard to understand.

2024-11-04 20:37 UTC, james-d-elliott requested changes

2024-11-05 05:58 UTC, james-d-elliott approved these changes

2024-11-05 06:02 UTC, merged