docs: add envoy gateway api section
authelia/authelia pull request #8262
Opened 2024-11-13 22:46 UTC by samos667

This a sample of how I've implemented it for now. This not perfect, (about SecurityPolicy spec accuracy and doc too), but I'll really appreciate to refine it.

For the documentation, I don't know if I need to go further about CR declaration and explanation. Don't hesitate to tell me how to redact this.

2024-11-13 22:49 UTC, samos667 commented
> ### ✅ Deploy Preview for _authelia-staging_ ready!
> Name	Link
> 🔨 Latest commit	[efb43de](https://github.com/authelia/authelia/commit/efb43de34085f75541f80c7e0e6f45e13e046bfb)
> 🔍 Latest deploy log	https://app.netlify.com/sites/authelia-staging/deploys/67352c2bf6dadc0008d09653
> 😎 Deploy Preview	https://deploy-preview-8262--authelia-staging.netlify.app
> 📱 Preview on mobile	
> Toggle QR Code...
> _To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/authelia-staging/configuration/notifications#deploy-webhooks)._

 Wow what a banger flow !!

2024-11-13 22:51 UTC, samos667 commented
For the lore btw
![image](https://github.com/user-attachments/assets/6e490c9e-03db-49fb-9337-cdbfc668bcaa)

2024-11-14 11:23 UTC, james-d-elliott requested changes

2024-11-14 11:23 UTC, james-d-elliott commented on docs/content/integration/proxies/envoy.md
> +If the route namespace differs from the authelia service namespace, there is a need to declare a ReferenceGrant:
```suggestion
If the route namespace differs from the authelia service namespace, there is a need to declare a ReferenceGrant:

```

2024-11-14 11:23 UTC, james-d-elliott commented on docs/content/integration/proxies/envoy.md
> +If the gateway namespace differs from the authelia service namespace, there is a need to declare a ReferenceGrant:
```suggestion
If the gateway namespace differs from the authelia service namespace, there is a need to declare a ReferenceGrant:

```

2024-11-14 11:24 UTC, james-d-elliott approved these changes

2024-11-14 11:34 UTC, merged

2024-11-14 11:35 UTC, james-d-elliott commented
Thanks for this! @all-contributors please add @samos667 for docs.