feat(handlers): basic authz caching
authelia/authelia pull request #8320
Opened 2024-11-24 21:49 UTC by james-d-elliott

This adds the ability to cache successful basic authz attempts.

2025-01-08 01:10 UTC, Crowley723 requested changes
Just some minor nitpicks regarding documentation for the new AuthHandler functions.

2025-01-08 01:10 UTC, Crowley723 commented on internal/handlers/handler_authz_authn.go
> +func NewCachedBasicAuthHandler(lifespan time.Duration) BasicAuthHandler {
```suggestion

// NewCachedBasicAuthHandler creates a BasicAuthHandler that caches valid credentials using HMAC.
// Returns a BasicAuthHandler function that handles authentication requests with caching.
func NewCachedBasicAuthHandler(lifespan time.Duration) BasicAuthHandler {
```

2025-02-23 12:28 UTC, archef2000 commented
Caching would be great as some requests nearly take 10ms.

2025-02-24 00:44 UTC, james-d-elliott commented on internal/authentication/cached.go
> +func (c *CredentialCacheHMAC) sum(username, password string) (sum []byte, err error) {
General practice for go for unexported functions is to not document them unless the purpose is not clear.

2025-02-24 03:03 UTC, Crowley723 requested changes

2025-02-24 07:49 UTC, merged