Feat rl middleware
authelia/authelia pull request #8321
Opened 2024-11-24 21:49 UTC by james-d-elliott

2025-02-28 01:22 UTC, Crowley723 requested changes
Just a couple questions.

2025-02-28 01:22 UTC, Crowley723 commented on internal/middlewares/rate_limiting.go
> +}
Question: Does holding the lock for the entire function make sense?

I am curious if the  `l.new()` call is fast enough that holding the lock while it executes is okay. Potentially this slows down bucket-miss handling. Every new bucket would have to wait for the currently executing one to complete memory allocation and initialization.
Would it be better to do an initial lock, check, unlock. Check if it already exists, if so, return. Otherwise create a new limiter (`l.NewLimiter()`) then lock, check again (in case another fetch added it already) then add the newLimiter and return.

Something like this
```go
func (l *IPRateLimitBucket) Fetch(key string) (limiter *RateLimiter) {
    l.mu.Lock()
    limiter, ok := l.bucket[key]
    l.mu.Unlock()
    
    if ok {
        return limiter
    }
    // pre-allocate and initialize non-existent limiter
    newLimiter := l.newLimiter(key);
    
    l.mu.Lock()
    defer l.mu.Unlock()
    
    //check again
    if limiter, ok = l.bucket[key]; ok {
        return limiter
    }
    
    l.bucket[key] = newLimiter
    return newLimiter
}
```

2025-02-28 01:22 UTC, Crowley723 commented on internal/middlewares/rate_limiting.go
> +					reservation := limiter.ReserveN(time.Now().UTC(), 1)
Question: Would it be beneficial to move the `reservation` logic to a helper function? 

Since its just here to check when the next token is available and not actually being used, its feels weird to have it here.

Something like `timeToNextToken()` might make more sense and would improve readability.

2025-02-28 06:33 UTC, james-d-elliott commented on internal/middlewares/rate_limiting.go
> +}
So I've tested something identical to this before, the benchmarks indicated at most a 3% difference (something like 10ns). I'd consider it a premature optimization in this situation since you can get even more performance by using a RWMutex (about 5-10% depending) and avoiding defer.

It's more likely to cause the introduction of bugs when making enhancements or fixes unless the performance impact is significant, at least in my opinion.

2025-02-28 06:36 UTC, james-d-elliott commented on internal/middlewares/rate_limiting.go
> +	}()
It's a good question but technically go will end all goroutines without calling defer. At least the last time I checked.

2025-02-28 06:37 UTC, james-d-elliott commented on web/src/views/Revoke/RevokeResetPasswordTokenView.tsx
> +            }
Yeah it'd be better in this instance, think this was introduced when refactoring and simplifying the API.

2025-02-28 06:49 UTC, james-d-elliott commented on internal/middlewares/rate_limiting.go
> +					reservation := limiter.ReserveN(time.Now().UTC(), 1)
```go
func NewRateLimiter(newBucket func(bucket RateLimitBucketConfig) RateLimitBucket, handler RequestHandler, bs ...RateLimitBucketConfig) AutheliaMiddleware {
	buckets := make([]RateLimitBucket, len(bs))

	for i, b := range bs {
		buckets[i] = newBucket(b)
	}

	if handler == nil {
		handler = HandlerRateLimitAPI
	}

	ticker := time.NewTicker(time.Minute * 30)

	go func() {
		for range ticker.C {
			for _, bucket := range buckets {
				bucket.GC()
			}
		}
	}()

	return func(next RequestHandler) RequestHandler {
		return func(ctx *AutheliaCtx) {
			var (
				retryAfter time.Duration
			)

			for i, bucket := range buckets {
				limiter := bucket.FetchCtx(ctx)

				if !limiter.Allow() {
					reservation := limiter.ReserveN(time.Now().UTC(), 1)
					limiter.updated = time.Now().UTC()

					ctx.Logger.WithFields(map[string]any{"bucket": i + 1, "delay": reservation.Delay().Seconds()}).Warn("Rate Limit Exceeded")

					if reservation.Delay() > retryAfter {
						retryAfter = reservation.Delay()
					}

					reservation.Cancel()
				}
			}

			if retryAfter > 0 {
				ctx.Response.Header.SetBytesK(headerRetryAfter, time.Now().UTC().Add(retryAfter).Format(http.TimeFormat))
				ctx.SetStatusCode(fasthttp.StatusTooManyRequests)

				handler(ctx)

				return
			}

			next(ctx)
		}
	}
}
```

vs

```go
func NewRateLimiter(newBucket func(bucket RateLimitBucketConfig) RateLimitBucket, handler RequestHandler, bs ...RateLimitBucketConfig) AutheliaMiddleware {
	buckets := make([]RateLimitBucket, len(bs))

	for i, b := range bs {
		buckets[i] = newBucket(b)
	}

	if handler == nil {
		handler = HandlerRateLimitAPI
	}

	ticker := time.NewTicker(time.Minute * 30)

	go func() {
		for range ticker.C {
			for _, bucket := range buckets {
				bucket.GC()
			}
		}
	}()

	timeToNextToken := func(ctx *AutheliaCtx, i int, bucket RateLimitBucket) (delay time.Duration) {
		limiter := bucket.FetchCtx(ctx)

		if !limiter.Allow() {
			reservation := limiter.ReserveN(time.Now().UTC(), 1)
			limiter.updated = time.Now().UTC()

			ctx.Logger.WithFields(map[string]any{"bucket": i + 1, "delay": reservation.Delay().Seconds()}).Warn("Rate Limit Exceeded")

			delay = reservation.Delay()

			reservation.Cancel()
		}

		return delay
	}

	return func(next RequestHandler) RequestHandler {
		return func(ctx *AutheliaCtx) {
			var (
				retryAfter time.Duration
			)

			for i, bucket := range buckets {
				delay := timeToNextToken(ctx, i, bucket)
				
				if delay > retryAfter {
					retryAfter = delay
				}
			}

			if retryAfter > 0 {
				ctx.Response.Header.SetBytesK(headerRetryAfter, time.Now().UTC().Add(retryAfter).Format(http.TimeFormat))
				ctx.SetStatusCode(fasthttp.StatusTooManyRequests)

				handler(ctx)

				return
			}

			next(ctx)
		}
	}
}
```

2025-02-28 16:15 UTC, Crowley723 commented on internal/middlewares/rate_limiting.go
> +					reservation := limiter.ReserveN(time.Now().UTC(), 1)
Fair enough. Considering the overall length of the function, it doesn't make much difference.

2025-02-28 16:37 UTC, Crowley723 approved these changes
👍

2025-03-01 03:13 UTC, james-d-elliott commented on internal/middlewares/rate_limiting.go
> +					reservation := limiter.ReserveN(time.Now().UTC(), 1)
Yeah I'm 50/50 on it, it would probably be a more obvious choice if it was reused. We can probably refactor it later if necessary.

2025-03-01 03:28 UTC, merged